name: Python application test with Github Actions
on: [push]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: action/setup-python@v3
      with: 
        python-version: 3.13
    - name: Install dependencies
      run: |
        make install
